#!/bin/bash

# Copyright 2012, Sean B. Palmer
# Code at http://inamidst.com/duxlot/
# Apache License 2.0

if [ ! -f duxlot ]
then echo Error: duxlot script not found
    exit 1
fi

./duxlot -f start test/test.json
